name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-contrib/golangci-lint@v1
      with:
        golangci_lint_version: v1.23
        args: run --config ./.golangci.yml ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - run: make test

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.4.0
      with:
        version: "v0.9.0"
        image: kindest/node:v1.14.10
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Setup
      run: |
        make install docker-build
        kind load docker-image ${IMAGE}:${TAG}
        (cd ./config/manager && kustomize edit set image controller=${IMAGE}:${TAG})
        kind load docker-image ${IMAGE}:${TAG}
        make deploy

        # NOTE: workaround to disable OpenAPI validation since it doesn't work
        # with field named as `items` on Kubernetes lesser than v1.16.0.
        # See more at:
        # - https://github.com/kubernetes/kubernetes/issues/68466
        # - https://github.com/kubernetes/kubernetes/pull/76124/files
        kubectl patch crds nginxes.nginx.tsuru.io --type=json --patch='[{"op": "replace", "path": "/spec/validation", "value": {}}]'
      env:
        IMAGE: tsuru/nginx-operator
        TAG: integration
    - run: |
        NGINX_OPERATOR_INTEGRATION=1 make test